In [125]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline

In [126]:
test = pd.read_csv('test.csv', index_col=False)

In [127]:
test.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl        NAmes      Feedr   
1         Lvl    AllPub    Corner       Gtl        NAmes       Norm   
2         Lvl    AllPub    Inside       Gtl      Gilbert       Norm   
3         Lvl    AllPub    Inside       Gtl      Gilbert       Norm   
4         HLS    AllPub    Inside       Gtl      StoneBr       Norm   

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     1Story            5            6       1961   
1       Norm     1Fam     1Story            6            6       1958   
2       Norm     1Fam     2Story            5            5       1997   
3       Norm     1Fam     2Story            6            6       1998   
4       Norm   TwnhsE     1Story            8            5       1992   

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          1961     Gable  CompShg     VinylSd     VinylSd       None   
1          1958       Hip  CompShg     Wd Sdng     Wd Sdng    BrkFace   
2          1998     Gable  CompShg     VinylSd     VinylSd       None   
3          1998     Gable  CompShg     VinylSd     VinylSd    BrkFace   
4          1992     Gable  CompShg     HdBoard     HdBoard       None   

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0         0.0        TA        TA     CBlock       TA       TA           No   
1       108.0        TA        TA     CBlock       TA       TA           No   
2         0.0        TA        TA      PConc       Gd       TA           No   
3        20.0        TA        TA      PConc       TA       TA           No   
4         0.0        Gd        TA      PConc       Gd       TA           No   

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0          Rec       468.0          LwQ       144.0      270.0        882.0   
1          ALQ       923.0          Unf         0.0      406.0       1329.0   
2          GLQ       791.0          Unf         0.0      137.0        928.0   
3          GLQ       602.0          Unf         0.0      324.0        926.0   
4          ALQ       263.0          Unf         0.0     1017.0       1280.0   

  Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0    GasA        TA          Y      SBrkr       896         0             0   
1    GasA        TA          Y      SBrkr      1329         0             0   
2    GasA        Gd          Y      SBrkr       928       701             0   
3    GasA        Ex          Y      SBrkr       926       678             0   
4    GasA        Ex          Y      SBrkr      1280         0             0   

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0        896           0.0           0.0         1         0             2   
1       1329           0.0           0.0         1         1             3   
2       1629           0.0           0.0         2         1             3   
3       1604           0.0           0.0         2         1             3   
4       1280           0.0           0.0         2         0             2   

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          TA             5        Typ           0         NaN   
1             1          Gd             6        Typ           0         NaN   
2             1          TA             6        Typ           1          TA   
3             1          Gd  

In [128]:
train = pd.read_csv('train.csv', index_col=False)


In [129]:
train.head()


Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1         Lvl    AllPub       FR2       Gtl      Veenker      Feedr   
2         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
3         Lvl    AllPub    Corner       Gtl      Crawfor       Norm   
4         Lvl    AllPub       FR2       Gtl      NoRidge       Norm   

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     2Story            7            5       2003   
1       Norm     1Fam     1Story            6            8       1976   
2       Norm     1Fam     2Story            7            5       2001   
3       Norm     1Fam     2Story            7            5       1915   
4       Norm     1Fam     2Story            8            5       2000   

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace   
1          1976     Gable  CompShg     MetalSd     MetalSd       None   
2          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace   
3          1970     Gable  CompShg     Wd Sdng     Wd Shng       None   
4          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace   

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0       196.0        Gd        TA      PConc       Gd       TA           No   
1         0.0        TA        TA     CBlock       Gd       TA           Gd   
2       162.0        Gd        TA      PConc       Gd       TA           Mn   
3         0.0        TA        TA     BrkTil       TA       Gd           No   
4       350.0        Gd        TA      PConc       Gd       TA           Av   

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0          GLQ         706          Unf           0        150          856   
1          ALQ         978          Unf           0        284         1262   
2          GLQ         486          Unf           0        434          920   
3          ALQ         216          Unf           0        540          756   
4          GLQ         655          Unf           0        490         1145   

  Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0    GasA        Ex          Y      SBrkr       856       854             0   
1    GasA        Ex          Y      SBrkr      1262         0             0   
2    GasA        Ex          Y      SBrkr       920       866             0   
3    GasA        Gd          Y      SBrkr       961       756             0   
4    GasA        Ex          Y      SBrkr      1145      1053             0   

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0       1710             1             0         2         1             3   
1       1262             0             1         2         0             3   
2       1786             1             0         2         1             3   
3       1717             1             0         1         0             3   
4       2198             1             0         2         1             4   

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          Gd             8        Typ           0         NaN   
1             1          TA             6        Typ           1          TA   
2             1          Gd             6        Typ           1          TA   
3             1          Gd            

In [130]:
train.shape

(1460, 81)

In [131]:
import scipy.stats

In [132]:
train = train.drop(columns=["Id"])

In [133]:
dataTypeDict = dict(train.dtypes)
arr=[]
for i in dataTypeDict:
    if dataTypeDict[i]=='O':
        arr.append(i)
print(arr)

['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']


In [134]:
for i in arr:
    train[i]=train[i].astype('category').cat.codes

In [135]:
# LotFrontage GarageYrBlt
train['LotFrontage'].fillna(train['LotFrontage'].mean(), inplace=True)

train['GarageYrBlt'].fillna(train['GarageYrBlt'].mean(), inplace=True)


In [136]:
result = (pd.Series([train['SalePrice'].corr(train[col]) for col in train], index=train.columns)
          .sort_values())
result = dict(result)
for i in result:
    print(i,result[i])

ExterQual -0.636883694399113
KitchenQual -0.5891887782994214
BsmtQual -0.43888096264893034
HeatingQC -0.40017754316290105
GarageFinish -0.2924833486295423
LotShape -0.2555798704871224
GarageType -0.22381853020674966
BsmtExposure -0.19307856748009564
Fence -0.18191133899219925
MSZoning -0.16687220265320618
KitchenAbvGr -0.1359073708421412
EnclosedPorch -0.12857795792595678
Heating -0.09881207599757652
Alley -0.09260744997351607
BldgType -0.08559060818352944
MSSubClass -0.08428413512659519
OverallCond -0.07785589404867799
MiscFeature -0.069316981463045
LotConfig -0.06739602315941753
SaleType -0.05491147712871201
YrSold -0.02892258516873033
LowQualFinSF -0.02560613000067955
MiscVal -0.021189579640303248
BsmtHalfBath -0.016844154297359002
Utilities -0.01431429614724877
BsmtFinType1 -0.013232907158195839
BsmtFinSF2 -0.011378121450215146
MasVnrType -0.000487789163367828
Condition2 0.007512734036333045
LandContour 0.015453241660960373
Street 0.041035535500049534
3SsnPorch 0.044583665335748396

In [137]:
pd.set_option("display.max_rows", 5, "display.max_columns", 10)

In [138]:
# for i in result:
#     if result[i]<0:
#         train = train.drop(columns=[i])

In [139]:
train.shape

(1460, 80)

In [140]:
train.loc[1260:,'SalePrice'].shape

(200,)

In [141]:
pd.set_option("display.max_rows", 5, "display.max_columns", 10)
train.iloc[:,0:80]

MSSubClass  MSZoning  LotFrontage  LotArea  Street  ...  MoSold  YrSold  \
0             60         3         65.0     8450       1  ...       2    2008   
1             20         3         80.0     9600       1  ...       5    2007   
...          ...       ...          ...      ...     ...  ...     ...     ...   
1458          20         3         68.0     9717       1  ...       4    2010   
1459          20         3         75.0     9937       1  ...       6    2008   

      SaleType  SaleCondition  SalePrice  
0            8              4     208500  
1            8              4     181500  
...        ...            ...        ...  
1458         8              4     142125  
1459         8              4     147500  

[1460 rows x 80 columns]

In [142]:
n=train.shape[1]
n

80

In [143]:
for i in train.columns:
    if train[i].isnull().sum()!=0:
        print(i,train[i].isnull().sum())


MasVnrArea 8


In [144]:
#MasVnrArea
train['MasVnrArea'].fillna(train['MasVnrArea'].mean(), inplace=True)


In [145]:
skew_df = pd.DataFrame(train.select_dtypes(np.number).columns, columns=['Feature'])
skew_df['Skew'] = skew_df['Feature'].apply(lambda feature: scipy.stats.skew(train[feature]))
skew_df['Absolute Skew'] = skew_df['Skew'].apply(abs)
skew_df['Skewed'] = skew_df['Absolute Skew'].apply(lambda x: True if x >= 0.5 else False)
pd.set_option("display.max_rows", None, "display.max_columns", None)
skew_df

Feature       Skew  Absolute Skew  Skewed
0      MSSubClass   1.406210       1.406210    True
1        MSZoning  -1.733612       1.733612    True
2     LotFrontage   2.382499       2.382499    True
3         LotArea  12.195142      12.195142    True
4          Street -15.502821      15.502821    True
5           Alley   4.284964       4.284964    True
6        LotShape  -0.609548       0.609548    True
7     LandContour  -3.159249       3.159249    True
8       Utilities  38.170678      38.170678    True
9       LotConfig  -1.134465       1.134465    True
10      LandSlope   4.808735       4.808735    True
11   Neighborhood   0.042078       0.042078   False
12     Condition1   3.016093       3.016093    True
13     Condition2  13.158307      13.158307    True
14       BldgType   2.243340       2.243340    True
15     HouseStyle   0.306439       0.306439   False
16    OverallQual   0.216721       0.216721   False
17    OverallCond   0.692355       0.692355    True
18      YearBuilt  -0.612831       0.612831    True
19   YearRemodAdd  -0.503044       0.503044    True
20      RoofStyle   1.472282       1.472282    True
21       RoofMatl   8.101068       8.101068    True
22    Exterior1st  -0.725567       0.725567    True
23    Exterior2nd  -0.692251       0.692251    True
24     MasVnrType  -0.413854       0.413854   False
25     MasVnrArea   2.673661       2.673661    True
26      ExterQual  -1.828384       1.828384    True
27      ExterCond  -2.562668       2.562668    True
28     Foundation   0.091124       0.091124   False
29       BsmtQual  -1.475216       1.475216    True
30       BsmtCond  -3.071656       3.071656    True
31   BsmtExposure  -1.136621       1.136621    True
32   BsmtFinType1  -0.057176       0.057176   False
33     BsmtFinSF1   1.683771       1.683771    True
34   BsmtFinType2  -3.188535       3.188535    True
35     BsmtFinSF2   4.250888       4.250888    True
36      BsmtUnfSF   0.919323       0.919323    True
37    TotalBsmtSF   1.522688       1.522688    True
38        Heating   9.844972       9.844972    True
39      HeatingQC   0.482722       0.482722   False
40     CentralAir  -3.526757       3.526757    True
41     Electrical  -3.048623       3.048623    True
42       1stFlrSF   1.375342       1.375342    True
43       2ndFlrSF   0.812194       0.812194    True
44   LowQualFinSF   9.002080       9.002080    True
45      GrLivArea   1.365156       1.365156    True
46   BsmtFullBath   0.595454       0.595454    True
47   BsmtHalfBath   4.099186       4.099186    True
48       FullBath   0.036524       0.036524   False
49       HalfBath   0.675203       0.675203    True
50   BedroomAbvGr   0.211572       0.211572   False
51   KitchenAbvGr   4.483784       4.483784    True
52    KitchenQual  -1.421346       1.421346    True
53   TotRmsAbvGrd   0.675646       0.675646    True
54     Functional  -4.080760       4.080760    True
55     Fireplaces   0.648898       0.648898    True
56    FireplaceQu   0.324613       0.324613   False
57     GarageType   0.606592       0.606592    True
58    GarageYrBlt  -0.667488       0.667488    True
59   GarageFinish  -0.531754       0.531754    True
60     GarageCars  -0.342197       0.342197   False
61     GarageArea   0.179796       0.179796   False
62     GarageQual  -3.002622       3.002622    True
63     GarageCond  -3.205068       3.205068    True
64     PavedDrive  -3.305538       3.305538    True
65     WoodDeckSF   1.539792       1.539792    True
66    OpenPorchSF   2.361912       2.361912    True
67  EnclosedPorch   3.086696       3.086696    True
68      3SsnPorch  10.293752      10.293752    True
69    ScreenPorch   4.117977       4.117977    True
70       PoolArea  14.813135      14.813135    True
71         PoolQC  16.718999      16.718999    True
72          Fence   1.961949       1.961949    True
73    MiscFeature   5.033387       5.033387    True
74        MiscVal  24.451640      24.451640    True
75         MoSold   0.211835       0.211835   False
76    

# Splitting data into test and train

In [146]:
x_train = np.reshape(train.iloc[:1260,0:n-1].values, (-1,n-1))
x_test = np.reshape(train.iloc[1260:,0:n-1].values, (-1,n-1))
y_train = np.reshape(train.loc[:1259,'SalePrice'].values, (-1,1))
y_test = np.reshape(train.loc[1260:,'SalePrice'].values, (-1,1))
# for i in range(24):
#     x_train[i] = (x_train[i] - x_train[i].min())/(x_train[i].max()-x_train[i].min())
#
print('Train - Predictors shape', x_train.shape)
print('Test - Predictors shape', x_test.shape)
print('Train - Target shape', y_train.shape)
print('Test - Target shape', y_test.shape)

print(x_train)

Train - Predictors shape (1260, 79)
Test - Predictors shape (200, 79)
Train - Target shape (1260, 1)
Test - Target shape (200, 1)
[[  60.    3.   65. ... 2008.    8.    4.]
 [  20.    3.   80. ... 2007.    8.    4.]
 [  60.    3.   68. ... 2008.    8.    4.]
 ...
 [  30.    3.   56. ... 2009.    8.    4.]
 [  80.    3.   59. ... 2008.    8.    4.]
 [  20.    3.   65. ... 2008.    8.    4.]]


# Linear Regression using Scikit

This is the linear regression model implemented using scikit library. 

In [147]:
cls = linear_model.LinearRegression()
#Fit method is used for fitting your training data into the model
cls.fit(x_train,y_train)

LinearRegression()

In [148]:
prediction = cls.predict(x_test)

In [149]:
#Parameters used for the model 
cls.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

In [150]:
print('Co-efficient of linear regression',cls.coef_)

Co-efficient of linear regression [[-7.92059504e+01 -1.14645681e+03  5.34291138e+01  4.49140466e-01
   3.29868260e+04 -2.79231024e+03 -4.13665595e+02  5.60439757e+02
  -3.85829078e+04 -7.27439523e+01  2.00196588e+03  3.59045357e+02
  -1.59549025e+03 -1.09559669e+04 -1.40834056e+03 -8.57841107e+01
   9.91444267e+03  5.54080015e+03  2.25370895e+02  5.10808893e+01
   3.98438377e+02  2.41670387e+03 -9.25867995e+02  5.75790278e+02
   4.43276342e+03  3.03803525e+01 -9.10827957e+03  7.98576173e+02
   1.14057037e+02 -8.17809941e+03  1.59222149e+03 -2.31665990e+03
   7.44007885e+01  1.65962918e+01  1.12790602e+03  1.32712214e+01
  -1.62532915e+00  2.82421842e+01 -8.11353695e+02 -7.74705605e+02
  -1.63521531e+03 -1.58017195e+02  1.83791087e+01  2.81380591e+01
  -2.34417933e+01  2.30753748e+01  1.91386058e+03 -6.86076395e+02
   1.12283420e+03  9.60097872e+02 -6.65014776e+03 -2.08360523e+04
  -6.38869266e+03  4.39705013e+03  3.52945869e+03  8.23165313e+03
  -1.67122174e+03  1.10775503e+03  1.19365

In [151]:
print('Intercept of linear regression model',cls.intercept_)

Intercept of linear regression model [1679657.33213879]


In [152]:
print('Mean Square Error', metrics.mean_squared_error(y_test, prediction))

Mean Square Error 2490446475.599499


In [153]:
print('Model R^2 Square value', metrics.r2_score(y_test, prediction))

Model R^2 Square value 0.51951750985273


# Linear Regression using Gradient Descent

In [154]:
def mse(slope, intercept, x_train, y_train):
    tot_error = 0
    pred = []
    for i in range(len(x_train)):
        #calculating total error. It follows the formula y=mx+c
        #m is the slope and c is the intercept
        pred.append(((slope*x_train[i]) + intercept))
        tot_error += (y_train[i] - ((slope*x_train[i]) + intercept)) ** 2
        
    error = tot_error / float(len(x_train))
    return error, pred

In [155]:
#gradient descent 
def grad_descent(s_slope, s_intercept, l_rate, iter_val, x_train, y_train):
    
    for i in range(iter_val):
        int_slope = 0
        int_intercept = 0
        n_pt = float(len(x_train))
        
        
        for i in range(len(x_train)):
            int_intercept += - (2/n_pt) * (y_train[i] - ((s_slope * x_train[i]) + s_intercept))
            int_slope += - (2/n_pt) * x_train[i] * (y_train[i] - ((s_slope * x_train[i]) + s_intercept))
            
        final_slope = s_slope - (l_rate * int_slope)
        final_intercept = s_intercept - (l_rate * int_intercept)
        s_slope = final_slope
        s_intercept = final_intercept
        
        
    return  s_slope, s_intercept

In [156]:
#defining slope and intercept value as 0 
learning_rate = 0.000001
start_slope = 0
start_intercept = 0
iteration = 1000
#intial run
grad_slope, grad_intercept = grad_descent(start_slope, start_intercept, learning_rate, iteration, x_train, y_train)
final_e_value, prediction = mse(grad_slope, grad_intercept, x_test, y_test)
#
print('Slope of the model', grad_slope)
print('Intercept of the model', grad_intercept)
print('Error value of the model', final_e_value)
r2_val = rsq(prediction, y_test)
print('R squared value', r2_val)
print(prediction,"\n\n")
print(y_test)


/var/folders/0r/m1xvx8c11c90xz17cp51blf00000gn/T/ipykernel_34456/4105773154.py:12: RuntimeWarning: overflow encountered in add
  int_slope += - (2/n_pt) * x_train[i] * (y_train[i] - ((s_slope * x_train[i]) + s_intercept))
/var/folders/0r/m1xvx8c11c90xz17cp51blf00000gn/T/ipykernel_34456/4105773154.py:12: RuntimeWarning: overflow encountered in multiply
  int_slope += - (2/n_pt) * x_train[i] * (y_train[i] - ((s_slope * x_train[i]) + s_intercept))
/var/folders/0r/m1xvx8c11c90xz17cp51blf00000gn/T/ipykernel_34456/4105773154.py:14: RuntimeWarning: invalid value encountered in subtract
  final_slope = s_slope - (l_rate * int_slope)


Slope of the model (79,)
Intercept of the model (79,)
Error value of the model (79,)


/var/folders/0r/m1xvx8c11c90xz17cp51blf00000gn/T/ipykernel_34456/203430121.py:8: RuntimeWarning: overflow encountered in square
  tot_error += (y_train[i] - ((slope*x_train[i]) + intercept)) ** 2


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [120]:
print('Error value of the model', final_e_value)

Error value of the model [1.82378791e+10 3.61891393e+10 1.56491897e+10            nan
 3.72032194e+10 3.73312848e+10 3.69188501e+10 3.63590375e+10
 3.73321600e+10 3.61915473e+10 3.73315374e+10 2.31421850e+10
 3.67857492e+10 3.68151067e+10 3.73052827e+10 3.60962321e+10
 3.21768833e+10 3.35786838e+10            nan            nan
 3.70393454e+10 3.71772745e+10 2.71700774e+10 2.58356313e+10
 3.63636005e+10 2.28760311e+10 3.66250049e+10 3.55473648e+10
 3.70393143e+10 3.61676942e+10 3.55222370e+10 3.61313037e+10
 3.56185274e+10 2.29830227e+10 3.33821337e+10 3.54313694e+10
 1.36939518e+10            inf 3.71945484e+10 3.71456708e+10
 3.72121919e+10 3.45003922e+10            inf 2.12234931e+10
 3.70557001e+10            nan 3.73013141e+10 3.73318591e+10
 3.69559837e+10 3.73074490e+10 3.62261653e+10 3.71931696e+10
 3.67517858e+10 3.16519062e+10 3.32670332e+10 3.72568217e+10
 3.66436885e+10 3.62363601e+10            nan 3.68445815e+10
 3.68224960e+10 4.49869011e+09 3.45673885e+10 3.45140742e+10

In [121]:
print(y_test)

[[181000]
 [128900]
 [161500]
 [180500]
 [181000]
 [183900]
 [122000]
 [378500]
 [381000]
 [144000]
 [260000]
 [185750]
 [137000]
 [177000]
 [139000]
 [137000]
 [162000]
 [197900]
 [237000]
 [ 68400]
 [227000]
 [180000]
 [150500]
 [139000]
 [169000]
 [132500]
 [143000]
 [190000]
 [278000]
 [281000]
 [180500]
 [119500]
 [107500]
 [162900]
 [115000]
 [138500]
 [155000]
 [140000]
 [160000]
 [154000]
 [225000]
 [177500]
 [290000]
 [232000]
 [130000]
 [325000]
 [202500]
 [138000]
 [147000]
 [179200]
 [335000]
 [203000]
 [302000]
 [333168]
 [119000]
 [206900]
 [295493]
 [208900]
 [275000]
 [111000]
 [156500]
 [ 72500]
 [190000]
 [ 82500]
 [147000]
 [ 55000]
 [ 79000]
 [130500]
 [256000]
 [176500]
 [227000]
 [132500]
 [100000]
 [125500]
 [125000]
 [167900]
 [135000]
 [ 52500]
 [200000]
 [128500]
 [123000]
 [155000]
 [228500]
 [177000]
 [155835]
 [108500]
 [262500]
 [283463]
 [215000]
 [122000]
 [200000]
 [171000]
 [134900]
 [410000]
 [235000]
 [170000]
 [110000]
 [149900]
 [177500]
 [315000]


In [122]:
print(prediction,"\n\n")


[array([ 1.19898304e+005,  3.55958797e+003, -2.34980095e+003,
                    nan,  7.21805667e+002,  3.61877852e+002,
        1.64147696e+003,  3.36274107e+003,  3.61880137e+002,
        1.41737259e+003,  3.61878611e+002,  3.15042792e+004,
        4.82765212e+003,  1.80958115e+003,  3.61801717e+002,
        6.09595884e+003,  1.41090544e+004,  1.00416534e+004,
                    nan,              nan,  8.97517414e+002,
        7.64651071e+002,  3.86679728e+004,  4.41903435e+004,
        3.31274628e+003,  2.43052083e+002,  2.88609648e+003,
        5.74123691e+003,  1.46005750e+003,  3.54712234e+003,
        5.73001274e+003,  4.75470738e+003,  8.04486260e+003,
        1.46394921e+002,  1.21434417e+004,  3.34698251e+002,
        1.79733708e+005, -3.70616500e+203,  7.30366056e+002,
        3.61183520e+002,  7.09329283e+002,  8.82396728e+003,
       -5.36307468e+298,  1.88365477e+005,  3.57938623e+002,
                    nan,  3.61808126e+002,  3.61878867e+002,
        1.58651645e+003