In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
test = pd.read_csv('test.csv', index_col=False)

In [3]:
test.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [4]:
train = pd.read_csv('train.csv', index_col=False)


In [5]:
train.head()


Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [6]:
train.shape

(1460, 81)

In [7]:
import scipy.stats

In [8]:
train = train.drop(columns=["Id"])

In [9]:
dataTypeDict = dict(train.dtypes)
arr=[]
for i in dataTypeDict:
    if dataTypeDict[i]=='O':
        arr.append(i)
print(arr)

['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']


In [10]:
for i in arr:
    train[i]=train[i].astype('category').cat.codes

In [11]:
# LotFrontage GarageYrBlt
train['LotFrontage'].fillna(train['LotFrontage'].mean(), inplace=True)

train['GarageYrBlt'].fillna(train['GarageYrBlt'].mean(), inplace=True)


In [12]:
result = (pd.Series([train['SalePrice'].corr(train[col]) for col in train], index=train.columns)
          .sort_values())
result = dict(result)
for i in result:
    print(i,result[i])

ExterQual -0.636883694399113
KitchenQual -0.5891887782994214
BsmtQual -0.43888096264893034
HeatingQC -0.40017754316290105
GarageFinish -0.2924833486295423
LotShape -0.2555798704871224
GarageType -0.22381853020674966
BsmtExposure -0.19307856748009564
Fence -0.18191133899219925
MSZoning -0.16687220265320618
KitchenAbvGr -0.1359073708421412
EnclosedPorch -0.12857795792595678
Heating -0.09881207599757652
Alley -0.09260744997351607
BldgType -0.08559060818352944
MSSubClass -0.08428413512659519
OverallCond -0.07785589404867799
MiscFeature -0.069316981463045
LotConfig -0.06739602315941753
SaleType -0.05491147712871201
YrSold -0.02892258516873033
LowQualFinSF -0.02560613000067955
MiscVal -0.021189579640303248
BsmtHalfBath -0.016844154297359002
Utilities -0.01431429614724877
BsmtFinType1 -0.013232907158195839
BsmtFinSF2 -0.011378121450215146
MasVnrType -0.000487789163367828
Condition2 0.007512734036333045
LandContour 0.015453241660960373
Street 0.041035535500049534
3SsnPorch 0.044583665335748396

In [13]:
pd.set_option("display.max_rows", 5, "display.max_columns", 10)

In [14]:
# for i in result:
#     if result[i]<0:
#         train = train.drop(columns=[i])

In [15]:
train.shape

(1460, 80)

In [16]:
train.loc[1260:,'SalePrice'].shape

(200,)

In [17]:
pd.set_option("display.max_rows", 5, "display.max_columns", 10)
train.iloc[:,0:80]

MSSubClass  MSZoning  LotFrontage  LotArea  Street  ...  MoSold  YrSold  \
0             60         3         65.0     8450       1  ...       2    2008   
1             20         3         80.0     9600       1  ...       5    2007   
...          ...       ...          ...      ...     ...  ...     ...     ...   
1458          20         3         68.0     9717       1  ...       4    2010   
1459          20         3         75.0     9937       1  ...       6    2008   

      SaleType  SaleCondition  SalePrice  
0            8              4     208500  
1            8              4     181500  
...        ...            ...        ...  
1458         8              4     142125  
1459         8              4     147500  

[1460 rows x 80 columns]

In [18]:
n=train.shape[1]
n

80

In [19]:
for i in train.columns:
    if train[i].isnull().sum()!=0:
        print(i,train[i].isnull().sum())


MasVnrArea 8


In [20]:
#MasVnrArea
train['MasVnrArea'].fillna(train['MasVnrArea'].mean(), inplace=True)


In [21]:
skew_df = pd.DataFrame(train.select_dtypes(np.number).columns, columns=['Feature'])
skew_df['Skew'] = skew_df['Feature'].apply(lambda feature: scipy.stats.skew(train[feature]))
skew_df['Absolute Skew'] = skew_df['Skew'].apply(abs)
skew_df['Skewed'] = skew_df['Absolute Skew'].apply(lambda x: True if x >= 0.5 else False)
pd.set_option("display.max_rows", None, "display.max_columns", None)
skew_df

Feature       Skew  Absolute Skew  Skewed
0      MSSubClass   1.406210       1.406210    True
1        MSZoning  -1.733612       1.733612    True
2     LotFrontage   2.382499       2.382499    True
3         LotArea  12.195142      12.195142    True
4          Street -15.502821      15.502821    True
5           Alley   4.284964       4.284964    True
6        LotShape  -0.609548       0.609548    True
7     LandContour  -3.159249       3.159249    True
8       Utilities  38.170678      38.170678    True
9       LotConfig  -1.134465       1.134465    True
10      LandSlope   4.808735       4.808735    True
11   Neighborhood   0.042078       0.042078   False
12     Condition1   3.016093       3.016093    True
13     Condition2  13.158307      13.158307    True
14       BldgType   2.243340       2.243340    True
15     HouseStyle   0.306439       0.306439   False
16    OverallQual   0.216721       0.216721   False
17    OverallCond   0.692355       0.692355    True
18      YearBuilt  -0.612831       0.612831    True
19   YearRemodAdd  -0.503044       0.503044    True
20      RoofStyle   1.472282       1.472282    True
21       RoofMatl   8.101068       8.101068    True
22    Exterior1st  -0.725567       0.725567    True
23    Exterior2nd  -0.692251       0.692251    True
24     MasVnrType  -0.413854       0.413854   False
25     MasVnrArea   2.673661       2.673661    True
26      ExterQual  -1.828384       1.828384    True
27      ExterCond  -2.562668       2.562668    True
28     Foundation   0.091124       0.091124   False
29       BsmtQual  -1.475216       1.475216    True
30       BsmtCond  -3.071656       3.071656    True
31   BsmtExposure  -1.136621       1.136621    True
32   BsmtFinType1  -0.057176       0.057176   False
33     BsmtFinSF1   1.683771       1.683771    True
34   BsmtFinType2  -3.188535       3.188535    True
35     BsmtFinSF2   4.250888       4.250888    True
36      BsmtUnfSF   0.919323       0.919323    True
37    TotalBsmtSF   1.522688       1.522688    True
38        Heating   9.844972       9.844972    True
39      HeatingQC   0.482722       0.482722   False
40     CentralAir  -3.526757       3.526757    True
41     Electrical  -3.048623       3.048623    True
42       1stFlrSF   1.375342       1.375342    True
43       2ndFlrSF   0.812194       0.812194    True
44   LowQualFinSF   9.002080       9.002080    True
45      GrLivArea   1.365156       1.365156    True
46   BsmtFullBath   0.595454       0.595454    True
47   BsmtHalfBath   4.099186       4.099186    True
48       FullBath   0.036524       0.036524   False
49       HalfBath   0.675203       0.675203    True
50   BedroomAbvGr   0.211572       0.211572   False
51   KitchenAbvGr   4.483784       4.483784    True
52    KitchenQual  -1.421346       1.421346    True
53   TotRmsAbvGrd   0.675646       0.675646    True
54     Functional  -4.080760       4.080760    True
55     Fireplaces   0.648898       0.648898    True
56    FireplaceQu   0.324613       0.324613   False
57     GarageType   0.606592       0.606592    True
58    GarageYrBlt  -0.667488       0.667488    True
59   GarageFinish  -0.531754       0.531754    True
60     GarageCars  -0.342197       0.342197   False
61     GarageArea   0.179796       0.179796   False
62     GarageQual  -3.002622       3.002622    True
63     GarageCond  -3.205068       3.205068    True
64     PavedDrive  -3.305538       3.305538    True
65     WoodDeckSF   1.539792       1.539792    True
66    OpenPorchSF   2.361912       2.361912    True
67  EnclosedPorch   3.086696       3.086696    True
68      3SsnPorch  10.293752      10.293752    True
69    ScreenPorch   4.117977       4.117977    True
70       PoolArea  14.813135      14.813135    True
71         PoolQC  16.718999      16.718999    True
72          Fence   1.961949       1.961949    True
73    MiscFeature   5.033387       5.033387    True
74        MiscVal  24.451640      24.451640    True
75         MoSold   0.211835       0.211835   False
76    

# Splitting data into test and train

In [22]:
x_train = np.reshape(train.iloc[:1260,0:n-1].values, (-1,n-1))
x_test = np.reshape(train.iloc[1260:,0:n-1].values, (-1,n-1))
y_train = np.reshape(train.loc[:1259,'SalePrice'].values, (-1,1))
y_test = np.reshape(train.loc[1260:,'SalePrice'].values, (-1,1))
# for i in range(24):
#     x_train[i] = (x_train[i] - x_train[i].min())/(x_train[i].max()-x_train[i].min())
#
print('Train - Predictors shape', x_train.shape)
print('Test - Predictors shape', x_test.shape)
print('Train - Target shape', y_train.shape)
print('Test - Target shape', y_test.shape)

print(x_train)

Train - Predictors shape (1260, 79)
Test - Predictors shape (200, 79)
Train - Target shape (1260, 1)
Test - Target shape (200, 1)
[[  60.    3.   65. ... 2008.    8.    4.]
 [  20.    3.   80. ... 2007.    8.    4.]
 [  60.    3.   68. ... 2008.    8.    4.]
 ...
 [  30.    3.   56. ... 2009.    8.    4.]
 [  80.    3.   59. ... 2008.    8.    4.]
 [  20.    3.   65. ... 2008.    8.    4.]]


# Linear Regression using Scikit

This is the linear regression model implemented using scikit library. 

In [23]:
cls = linear_model.LinearRegression()
#Fit method is used for fitting your training data into the model
cls.fit(x_train,y_train)

LinearRegression()

In [24]:
prediction = cls.predict(x_test)

In [25]:
#Parameters used for the model 
cls.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

In [26]:
print('Co-efficient of linear regression',cls.coef_)

Co-efficient of linear regression [[-7.92059504e+01 -1.14645681e+03  5.34291138e+01  4.49140466e-01
   3.29868260e+04 -2.79231024e+03 -4.13665595e+02  5.60439757e+02
  -3.85829078e+04 -7.27439523e+01  2.00196588e+03  3.59045357e+02
  -1.59549025e+03 -1.09559669e+04 -1.40834056e+03 -8.57841107e+01
   9.91444267e+03  5.54080015e+03  2.25370895e+02  5.10808893e+01
   3.98438377e+02  2.41670387e+03 -9.25867995e+02  5.75790278e+02
   4.43276342e+03  3.03803525e+01 -9.10827957e+03  7.98576173e+02
   1.14057037e+02 -8.17809941e+03  1.59222149e+03 -2.31665990e+03
   7.44007885e+01  1.65962918e+01  1.12790602e+03  1.32712214e+01
  -1.62532915e+00  2.82421842e+01 -8.11353695e+02 -7.74705605e+02
  -1.63521531e+03 -1.58017195e+02  1.83791087e+01  2.81380591e+01
  -2.34417933e+01  2.30753748e+01  1.91386058e+03 -6.86076395e+02
   1.12283420e+03  9.60097872e+02 -6.65014776e+03 -2.08360523e+04
  -6.38869266e+03  4.39705013e+03  3.52945869e+03  8.23165313e+03
  -1.67122174e+03  1.10775503e+03  1.19365

In [27]:
print('Intercept of linear regression model',cls.intercept_)

Intercept of linear regression model [1679657.33213879]


In [28]:
print('Mean Square Error', metrics.mean_squared_error(y_test, prediction))

Mean Square Error 2490446475.599499


In [29]:
print('Model R^2 Square value', metrics.r2_score(y_test, prediction))

Model R^2 Square value 0.51951750985273


# Linear Regression using Gradient Descent

In [30]:
def mse(slope, x_train, y_train):
    tot_error = 0
    pred = []

    pred.append(np.dot(x_train,slope))
    tot_error += (y_train - (np.dot(x_train,slope)))** 2
    
    error = tot_error / (2*float(len(x_train)))
    return error, pred

In [31]:
#gradient descent 
def grad_descent(s_slope, l_rate, iter_val, x_train, y_train):
    
    
    for i in range(iter_val):
        n_data = x_train.shape[1]
        int_slope = np.ones((n_data+1,1))  
        
        print(y_train.shape,x_train.shape,s_slope.shape,np.dot( x_train,s_slope).shape ,np.transpose(x_train).shape,(y_train - (np.dot( x_train,s_slope))).shape)

        print(i)
        int_slope += - (2/n_data) * np.dot(np.transpose(x_train), (y_train - (np.dot( x_train,s_slope))))
            
        final_slope = s_slope - (l_rate * int_slope)

        s_slope = final_slope
        
        
    return  s_slope

In [32]:
#defining slope and intercept value as 0 
learning_rate = 0.0001

n_data = x_train.shape[1]

start_slope = np.ones((n_data+1,1))
bias = np.ones(( x_train.shape[0],1))
x_train_b = np.append(bias, x_train, axis=1)

iteration = 100
#intial run
grad_slope = grad_descent(start_slope, learning_rate, iteration, x_train_b, y_train)
final_e_value, prediction = mse(grad_slope, x_test, y_test)
#
print(np.array(prediction).shape,"\n\n")
print(y_test)


(1260, 1) (1260, 80) (80, 1) (1260, 1) (80, 1260) (1260, 1)
0


ValueError: operands could not be broadcast together with shapes (81,1) (80,1) (81,1) 


print('Slope of the model', grad_slope)
print('Intercept of the model', grad_intercept)
print('Error value of the model', final_e_value)

r2_val = metrics.r2_scoreq(prediction, y_test)
print('R squared value', r2_val)